FROM mcr.microsoft.com/dotnet/sdk:6.0

RUN mkdir /restore-dir

WORKDIR /restore-dir

COPY ./Main.csproj .
COPY ./exec.sh .
RUN chmod +x ./exec.sh

RUN dotnet restore

# user to execute commands in container
RUN addgroup --system --gid 1000 executor \
    && adduser --system --uid 1000 --ingroup executor --shell /bin/bash executor

USER executor

